/* Chassis, an embedded vector index for local semantic search - C API */

/* Thread safety: every function but chassis_free may be called from any thread on a shared
   handle. Searches run concurrently; adds, deletes and flushes take the handle's write lock.
   chassis_free must not race any other call. A reader handle runs one call at a time. */


#ifndef CHASSIS_H
#define CHASSIS_H

#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * No error: what `chassis_last_error_code` returns after a call that succeeded.
 */
#define CHASSIS_OK 0

/**
 * An argument is out of range or malformed: a NULL pointer, dimensions, an option, an id, a
 * vector with a component that isn't a finite number.
 */
#define CHASSIS_ERROR_INVALID_ARGUMENT 1

/**
 * A vector or query has another number of components than the index's vectors, or the file
 * holds vectors of other dimensions than asked for.
 */
#define CHASSIS_ERROR_DIMENSION_MISMATCH 2

/**
 * The file was created with another metric or precision than the one asked for.
 */
#define CHASSIS_ERROR_OPTIONS_MISMATCH 3

/**
 * There is no index at the path, or its directory doesn't exist.
 */
#define CHASSIS_ERROR_NOT_FOUND 4

/**
 * The file is not a Chassis index.
 */
#define CHASSIS_ERROR_NOT_AN_INDEX 5

/**
 * The id is already in use.
 */
#define CHASSIS_ERROR_ID_IN_USE 6

/**
 * Another writer has the index open.
 */
#define CHASSIS_ERROR_LOCKED 7

/**
 * The handle is a reader, which only searches.
 */
#define CHASSIS_ERROR_READ_ONLY 8

/**
 * The file is damaged.
 */
#define CHASSIS_ERROR_CORRUPT 9

/**
 * The index can hold no more.
 */
#define CHASSIS_ERROR_FULL 10

/**
 * The operating system refused: permissions, a full disk, a failed read or write.
 */
#define CHASSIS_ERROR_IO 11

/**
 * Anything else, a panic included.
 */
#define CHASSIS_ERROR_OTHER 12

/**
 * Opaque handle to a Chassis index (C-compatible)
 *
 * This is a zero-sized type that serves as an opaque handle for C.
 * C code only sees pointers to this type, never the actual struct.
 * The real data is stored in `ChassisIndexState`.
 */
typedef struct ChassisIndex {
  uint8_t _private[0];
} ChassisIndex;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Open or create a Chassis vector index
 *
 * # Arguments
 *
 * - `path`: UTF-8 encoded path to the index file (must not be NULL)
 * - `dimensions`: Number of dimensions per vector (must be > 0)
 *
 * # Returns
 *
 * - Non-NULL pointer on success
 * - NULL on failure (check `chassis_last_error_message()`)
 *
 * # Thread Safety
 *
 * - Safe to call from multiple threads with different paths
 * - The returned handle may be shared across threads (see the crate's Thread Safety notes)
 *
 * # Example (C)
 *
 * ```c
 * ChassisIndex* index = chassis_open("vectors.chassis", 768);
 * if (index == NULL) {
 *     fprintf(stderr, "Error: %s\n", chassis_last_error_message());
 *     exit(1);
 * }
 * ```
 *
 * # Safety
 *
 * - `path` must be a valid, NULL-terminated UTF-8 string
 * - `path` must remain valid for the duration of this call
 * - Caller must free the returned pointer with `chassis_free()`
 */
struct ChassisIndex *chassis_open(const char *path, uint32_t dimensions);

/**
 * Open or create a Chassis vector index with custom options
 *
 * # Arguments
 *
 * - `path`: UTF-8 encoded path to the index file (must not be NULL)
 * - `dimensions`: Number of dimensions per vector (must be > 0)
 * - `max_connections`: Maximum connections per node (M parameter, typically 8-64)
 * - `ef_construction`: Construction quality (typically 100-400)
 * - `ef_search`: Search quality (typically 50-200)
 *
 * # Returns
 *
 * - Non-NULL pointer on success
 * - NULL on failure (check `chassis_last_error_message()`)
 *
 * # Parameter Guidelines
 *
 * - **max_connections (M)**: Higher = better recall, more memory. Default: 16
 * - **ef_construction**: Higher = better index quality, slower build. Default: 200
 * - **ef_search**: Higher = better search quality, slower search. Default: 50
 *
 * # Safety
 *
 * Same safety requirements as `chassis_open()`
 */
struct ChassisIndex *chassis_open_with_options(const char *path, uint32_t dimensions, uint32_t max_connections, uint32_t ef_construction, uint32_t ef_search);

/**
 * Open or create a Chassis vector index with custom options and a distance metric
 *
 * # Arguments
 *
 * - `metric`: `0` for Euclidean (L2) distance, `1` for cosine distance (1 - cosine similarity).
 *   A cosine index stores vectors scaled to unit length, rejects zero vectors, and reports
 *   distances from 0 to 2. The metric is fixed when the index is created; reopening an existing
 *   index with another one fails.
 * - The other arguments are as for `chassis_open_with_options()`.
 *
 * # Safety
 *
 * Same safety requirements as `chassis_open()`
 */
struct ChassisIndex *chassis_open_with_metric(const char *path, uint32_t dimensions, uint32_t max_connections, uint32_t ef_construction, uint32_t ef_search, uint32_t metric);

/**
 * Open or create a Chassis vector index with custom options, a distance metric and a precision
 *
 * # Arguments
 *
 * - `precision`: `0` to keep each component of a vector as a 32-bit float, `1` as a 16-bit
 *   float (half precision). Half precision halves the vectors' size in the file and in memory;
 *   each component is rounded to about three decimal digits, and a vector with a component of
 *   65,520 or more in magnitude is refused. The precision is fixed when the index is created;
 *   reopening an existing index with another one fails. A release without this function can't
 *   open a file in half precision.
 * - The other arguments are as for `chassis_open_with_metric()`.
 *
 * # Safety
 *
 * Same safety requirements as `chassis_open()`
 */
struct ChassisIndex *chassis_open_with_precision(const char *path, uint32_t dimensions, uint32_t max_connections, uint32_t ef_construction, uint32_t ef_search, uint32_t metric, uint32_t precision);

/**
 * Open an index to search it while a writer, possibly in another process, adds to it
 *
 * Takes no lock, so any number of readers can open the file next to one writer. Every search
 * first takes a new snapshot: it returns what the writer's last flush committed, and nothing that
 * flush deleted. Adds, deletes and flushes on the handle fail. The file must already exist in the
 * current format: open it once with `chassis_open` to create or migrate it.
 *
 * # Arguments
 *
 * - `path`: UTF-8 encoded path to the index file (must not be NULL)
 * - `dimensions`: Number of dimensions per vector (must be > 0)
 * - `max_connections`: The value the index was created with (16 by default)
 * - `ef_search`: Search quality parameter
 *
 * # Returns
 *
 * - Non-NULL pointer on success; free it with `chassis_free()`
 * - NULL on failure (check `chassis_last_error_message()`)
 *
 * # Safety
 *
 * Same safety requirements as `chassis_open()`
 */
struct ChassisIndex *chassis_open_reader(const char *path, uint32_t dimensions, uint32_t max_connections, uint32_t ef_search);

/**
 * Free a Chassis index and release all resources
 *
 * # Arguments
 *
 * - `ptr`: Pointer returned by `chassis_open()` or NULL
 *
 * # Safety
 *
 * - `ptr` must be NULL or a valid pointer from `chassis_open()`
 * - After this call, `ptr` is invalid and must not be used
 * - Safe to call with NULL (no-op)
 * - Must not be called more than once with the same non-NULL pointer
 *
 * # Example (C)
 *
 * ```c
 * chassis_free(index);
 * index = NULL; // Good practice
 * ```
 */
void chassis_free(struct ChassisIndex *ptr);

/**
 * Add a vector to the index
 *
 * # Arguments
 *
 * - `ptr`: Non-NULL pointer to index
 * - `vector`: Pointer to f32 array (must not be NULL)
 * - `len`: Number of elements in vector (must match index dimensions)
 *
 * # Returns
 *
 * - The id assigned (one past the largest id used so far) on success
 * - `UINT64_MAX` on failure (check `chassis_last_error_message()`)
 *
 * # Thread Safety
 *
 * Safe from any thread. Writes run one at a time; searches wait for them.
 *
 * # Performance Note
 *
 * This operation does NOT guarantee durability. Call `chassis_flush()` to
 * ensure data is written to disk.
 *
 * # Example (C)
 *
 * ```c
 * float vec[768] = {0.1, 0.2, ...};
 * u64 id = chassis_add(index, vec, 768);
 * if (id == UINT64_MAX) {
 *     fprintf(stderr, "Add failed: %s\n", chassis_last_error_message());
 * }
 * ```
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 * - `vector` must point to `len` valid f32 values
 * - `len` must match the dimensions specified in `chassis_open()`
 */
uint64_t chassis_add(struct ChassisIndex *ptr, const float *vector, size_t len);

/**
 * Add multiple vectors to the index in one call (row-major layout), linking them on every core
 *
 * # Arguments
 *
 * - `ptr`: Non-NULL pointer to index
 * - `vectors`: Contiguous `count * dim` floats: row `i` is
 *   `vectors[i*dim .. (i+1)*dim]`
 * - `count`: Number of vectors to insert
 * - `dim`: Elements per vector (must match index dimensions)
 * - `out_ids`: Output buffer for assigned IDs, length at least `count` (if `count > 0`)
 *
 * # Returns
 *
 * - `count` on success
 * - `0` on failure, with none of the batch added; use `chassis_last_error_message()` for the
 *   reason
 * - If `count == 0`, returns `0` and succeeds (pointers need not be valid)
 *
 * # Thread Safety
 *
 * Same as `chassis_add()`. The whole batch holds the write lock.
 *
 * # Performance Note
 *
 * Links the batch on every core, so a large batch builds many times faster than adding one
 * vector at a time; the graph then depends on thread timing. Does not by itself change
 * durability: call `chassis_flush()` when you need data on disk.
 *
 * # Example (C)
 *
 * ```c
 * float *batch; // count * dim elements, row-major
 * uint64_t ids[1000];
 * size_t n = chassis_add_batch(index, batch, 1000, 768, ids);
 * if (n == 0) {
 *     fprintf(stderr, "Batch add failed: %s\n", chassis_last_error_message());
 * }
 * ```
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 * - If `count > 0`, `vectors` and `out_ids` must be non-NULL; `vectors` must point
 *   to `count * dim` valid floats
 * - `dim` must match dimensions passed to `chassis_open()`
 */
size_t chassis_add_batch(struct ChassisIndex *ptr, const float *vectors, size_t count, size_t dim, uint64_t *out_ids);

/**
 * Add a vector under the caller's id
 *
 * # Returns
 *
 * - `0` on success
 * - `-1` on failure, including when a live vector already has `id` or `id` is `UINT64_MAX`
 *   (check `chassis_last_error_message()`)
 *
 * # Safety
 *
 * Same as `chassis_add()`.
 */
int chassis_add_with_id(struct ChassisIndex *ptr, uint64_t id, const float *vector, size_t len);

/**
 * Add multiple vectors under the caller's ids in one call, linking them on every core
 *
 * `ids[i]` is the id of row `i` of `vectors` (`count * dim` floats, row-major).
 *
 * # Returns
 *
 * - `0` on success, including when `count == 0`
 * - `-1` on failure, with none of the batch added: an id repeats, already exists or is
 *   `UINT64_MAX`, or the dimensions don't match (check `chassis_last_error_message()`)
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 * - If `count > 0`, `ids` must point to `count` ids and `vectors` to `count * dim` floats
 */
int chassis_add_batch_with_ids(struct ChassisIndex *ptr, const uint64_t *ids, const float *vectors, size_t count, size_t dim);

/**
 * Delete the vector with `id`
 *
 * Search stops returning it immediately; the delete is durable after the next
 * `chassis_flush()`.
 *
 * # Returns
 *
 * - `1` if it was deleted
 * - `0` if no live vector has `id`
 * - `-1` on failure (check `chassis_last_error_message()`)
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 */
int chassis_delete(struct ChassisIndex *ptr, uint64_t id);

/**
 * Search for k nearest neighbors
 *
 * # Arguments
 *
 * - `ptr`: Non-NULL pointer to index (shared access allowed)
 * - `query`: Pointer to query vector (must not be NULL)
 * - `len`: Number of elements in query (must match index dimensions)
 * - `k`: Number of neighbors to find (must be > 0)
 * - `out_ids`: Output buffer for vector IDs (must have space for k elements)
 * - `out_dists`: Output buffer for distances (must have space for k elements)
 *
 * # Returns
 *
 * - Number of results found (≤ k) on success
 * - 0 on failure (check `chassis_last_error_message()`)
 *
 * # Thread Safety
 *
 * Safe from any thread. Searches run concurrently with each other and wait for writes.
 *
 * # Output Format
 *
 * Results are sorted by distance (ascending):
 * - `out_ids[0]` = closest vector ID
 * - `out_dists[0]` = distance to closest vector
 *
 * # Example (C)
 *
 * ```c
 * float query[768] = {0.1, 0.2, ...};
 * u64 ids[10];
 * float dists[10];
 *
 * size_t count = chassis_search(index, query, 768, 10, ids, dists);
 * for (size_t i = 0; i < count; i++) {
 *     printf("ID: %llu, Distance: %f\n", ids[i], dists[i]);
 * }
 * ```
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 * - `query` must point to `len` valid f32 values
 * - `out_ids` must have space for at least `k` u64 values
 * - `out_dists` must have space for at least `k` float values
 * - Buffers must not overlap
 */
size_t chassis_search(const struct ChassisIndex *ptr, const float *query, size_t len, size_t k, uint64_t *out_ids, float *out_dists);

/**
 * Search for the k nearest neighbors among the given ids
 *
 * # Arguments
 *
 * - `allowed_ids`: The ids results may have; ids not in the index are ignored. May be NULL when
 *   `allowed_len` is 0, which matches nothing.
 * - `allowed_len`: Number of ids in `allowed_ids`
 * - The other arguments are as for `chassis_search()`.
 *
 * When walking the graph would cost more, as when few vectors match, the search checks every
 * vector instead and returns the exact nearest.
 *
 * # Returns
 *
 * As for `chassis_search()`.
 *
 * # Safety
 *
 * As for `chassis_search()`, and `allowed_ids` must point to `allowed_len` valid u64 values.
 */
size_t chassis_search_filtered(const struct ChassisIndex *ptr, const float *query, size_t len, size_t k, const uint64_t *allowed_ids, size_t allowed_len, uint64_t *out_ids, float *out_dists);

/**
 * Search for the k nearest neighbors of each of many queries, in one call
 *
 * # Arguments
 *
 * - `ptr`: Non-NULL pointer to index
 * - `queries`: `count` queries of `dim` components each, one after another
 * - `count`: Number of queries
 * - `dim`: Components per query: the index's dimensions
 * - `k`: Number of results per query
 * - `out_ids`, `out_dists`: Space for `count * k` values each. Row `i`, the `k` values from
 *   `i * k`, receives query `i`'s results, nearest first; a row with fewer than `k` is filled
 *   out with id `UINT64_MAX`, which no vector has, and distance `INFINITY`.
 *
 * # Returns
 *
 * - `count` on success
 * - 0 on failure (check `chassis_last_error_message()`), or for an empty batch, which sets no
 *   error; the rows before a query that failed hold its predecessors' results
 *
 * # Thread Safety
 *
 * Safe from any thread. Runs concurrently with other searches; a write waits for the whole batch.
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 * - `queries` must point to `count * dim` valid f32 values
 * - `out_ids` and `out_dists` must have space for `count * k` values each, and not overlap
 */
size_t chassis_search_batch(const struct ChassisIndex *ptr, const float *queries, size_t count, size_t dim, size_t k, uint64_t *out_ids, float *out_dists);

/**
 * Flush all changes to disk
 *
 * # Arguments
 *
 * - `ptr`: Non-NULL pointer to index
 *
 * # Returns
 *
 * - 0 on success
 * - -1 on failure (check `chassis_last_error_message()`)
 *
 * # Thread Safety
 *
 * Safe from any thread. Writes run one at a time; searches wait for them.
 *
 * # Performance Warning
 *
 * This operation is expensive (1-50ms depending on storage device).
 * Batch multiple `chassis_add()` calls and flush once at the end.
 *
 * # Example (C)
 *
 * ```c
 * // Add many vectors
 * for (int i = 0; i < 1000; i++) {
 *     chassis_add(index, vectors[i], 768);
 * }
 *
 * // Flush once at the end
 * if (chassis_flush(index) != 0) {
 *     fprintf(stderr, "Flush failed: %s\n", chassis_last_error_message());
 * }
 * ```
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 */
int chassis_flush(struct ChassisIndex *ptr);

/**
 * Ask the operating system to keep the index's vectors on huge pages
 *
 * On an index too large for the CPU's caches, searches are up to a quarter faster and batch
 * builds a little faster. Only on Linux, and only where the kernel and filesystem keep files on huge
 * pages (ext4 on Linux 6.17 does); elsewhere this does nothing. It is off unless asked for: with
 * it a page not yet in memory is read 2 MB at a time, which an index much larger than memory
 * pays for on every miss. Call it right after opening, on a writer's handle or a reader's.
 *
 * # Arguments
 *
 * - `ptr`: Non-NULL pointer to index
 *
 * # Returns
 *
 * - 0 on success
 * - -1 on failure (check `chassis_last_error_message()`)
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 */
int chassis_use_huge_pages(struct ChassisIndex *ptr);

/**
 * Start reading the whole index into memory on another thread
 *
 * Doesn't wait for the reading: searches go on meanwhile and stop waiting for the disk one page
 * at a time as the index arrives. For an index that fits in memory: one much larger would push
 * everything else out. What is read is what the index holds when this is called; while that is
 * under way, calling again does nothing. A reader that opens the file again after a compaction
 * reads the new one in too. It takes Linux 5.14 or macOS: an older Linux reads only some of the
 * index, and Windows none. Call it on a writer's handle or a reader's, right after opening or
 * later.
 *
 * # Arguments
 *
 * - `ptr`: Non-NULL pointer to index
 *
 * # Returns
 *
 * - 0 once asked, whether or not this system can do it
 * - -1 on failure (check `chassis_last_error_message()`)
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 */
int chassis_warm(struct ChassisIndex *ptr);

/**
 * Rewrite the index without its deleted vectors and with a newly built graph
 *
 * Reclaims the space of deleted vectors and replaces the index file with the copy. Ids don't
 * change. Like `chassis_flush()`, it makes every add and delete so far durable. Takes as long
 * as building the index, on every core, and needs free disk for a second copy of the live
 * vectors. Readers in other processes keep searching and move to the new file by themselves.
 *
 * # Returns
 *
 * - `0` on success
 * - `-1` on failure, with the index left as it was (check `chassis_last_error_message()`). On
 *   Windows it fails while another process has the index open.
 *
 * # Thread Safety
 *
 * Same as `chassis_flush()`: it holds the write lock, so searches on this handle wait.
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 */
int chassis_compact(struct ChassisIndex *ptr);

/**
 * Get the number of vectors in the index
 *
 * # Arguments
 *
 * - `ptr`: Non-NULL pointer to index (shared access)
 *
 * # Returns
 *
 * - Number of vectors, or 0 if `ptr` is NULL
 *
 * # Thread Safety
 *
 * Safe to call concurrently with `chassis_search()`.
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 */
uint64_t chassis_len(const struct ChassisIndex *ptr);

/**
 * Check if the index is empty
 *
 * # Arguments
 *
 * - `ptr`: Non-NULL pointer to index (shared access)
 *
 * # Returns
 *
 * - 1 if empty, 0 if not empty or `ptr` is NULL
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 */
int chassis_is_empty(const struct ChassisIndex *ptr);

/**
 * Get the dimensionality of vectors in the index
 *
 * # Arguments
 *
 * - `ptr`: Non-NULL pointer to index (shared access)
 *
 * # Returns
 *
 * - Number of dimensions, or 0 if `ptr` is NULL
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 */
uint32_t chassis_dimensions(const struct ChassisIndex *ptr);

/**
 * Get the distance metric the index was created with
 *
 * # Returns
 *
 * - `0` for Euclidean, `1` for cosine, as for `chassis_open_with_metric()`
 * - `-1` if `ptr` is NULL
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 */
int chassis_metric(const struct ChassisIndex *ptr);

/**
 * Get the precision the index keeps its vectors in
 *
 * # Returns
 *
 * - `0` for full precision, `1` for half, as for `chassis_open_with_precision()`
 * - `-1` if `ptr` is NULL
 *
 * # Safety
 *
 * - `ptr` must be non-NULL and valid
 */
int chassis_precision(const struct ChassisIndex *ptr);

/**
 * Get the last error message for the current thread
 *
 * # Returns
 *
 * - Pointer to NULL-terminated error string
 * - NULL if no error occurred
 *
 * # Thread Safety
 *
 * Each thread has its own error message storage. Safe to call from multiple
 * threads concurrently.
 *
 * # Lifetime
 *
 * The returned pointer is valid until:
 * - The next FFI function call on this thread
 * - The thread exits
 *
 * **Do NOT** free the returned pointer.
 *
 * # Example (C)
 *
 * ```c
 * if (chassis_add(index, vec, 768) == UINT64_MAX) {
 *     const char* error = chassis_last_error_message();
 *     if (error != NULL) {
 *         fprintf(stderr, "Error: %s\n", error);
 *     }
 * }
 * ```
 */
const char *chassis_last_error_message(void);

/**
 * What the last error on this thread was, for a program to act on
 *
 * # Returns
 *
 * One of the `CHASSIS_ERROR_` constants, or `CHASSIS_OK` (0) if the last call succeeded or set
 * no error. `chassis_last_error_message` says the same in words, with what to do instead.
 *
 * # Example (C)
 *
 * ```c
 * ChassisIndex* index = chassis_open("vectors.chassis", 768);
 * if (index == NULL && chassis_last_error_code() == CHASSIS_ERROR_LOCKED) {
 *     index = chassis_open_reader("vectors.chassis", 768, 16, 50);
 * }
 * ```
 */
int chassis_last_error_code(void);

/**
 * Get the Chassis library version
 *
 * # Returns
 *
 * Pointer to NULL-terminated version string (e.g., "0.1.0")
 *
 * # Lifetime
 *
 * The returned pointer is valid for the lifetime of the program.
 * **Do NOT** free the returned pointer.
 *
 * # Example (C)
 *
 * ```c
 * printf("Chassis version: %s\n", chassis_version());
 * ```
 */
const char *chassis_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CHASSIS_H */
